require_relative '../../node_modules/.pnpm/@capacitor+ios@7.4.2_@capacitor+core@7.4.2/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@7.4.2_@capacitor+core@7.4.2/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@7.4.2_@capacitor+core@7.4.2/node_modules/@capacitor/ios'
  pod 'CapacitorPasskeyPlugin', :path => '../../node_modules/.pnpm/capacitor-passkey-plugin@0.0.3_@capacitor+core@7.4.2/node_modules/capacitor-passkey-plugin'
  pod 'CapacitorPasskeyPlugin', :path => '../../node_modules/.pnpm/capacitor-passkey-plugin@0.0.3_@capacitor+core@7.4.2/node_modules/capacitor-passkey-plugin'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
