[package]
name = "smart-wallets-data-multi-signer-multi-sig"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
zephyr-sdk = "0.2.3"
stellar-strkey = "0.0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
webauthn-wallet-interface = { path = "../contracts/webauthn-wallet-interface" }
hex = "0.4.3"
base64 = "0.22.1"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
